/* eslint-disable */
var img = new Image();
window.phetImages.push( img );
img.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAG4AAAAWCAIAAACuSD4AAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAGhJREFUeNrs0rENwDAIAMHEpHFjiY1ZGaiRMkIaCjv6H+H0t5ld1NEz50Shh1JVUYASSijpg3KthUIPpYigAOVmlGMMFKDcjLKqUOihzEwUeigjAgUoofwrpbujwJVQQklQQnlarwADAKkHIlinYFEVAAAAAElFTkSuQmCC';
export default img;
